"""initial schema v1.1

Revision ID: c77dbd35bd12
Revises:
Create Date: 2026-07-25 19:43:01.463651
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c77dbd35bd12"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tier", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("calendar", sa.String(length=32), nullable=False),
        sa.Column("point_in_time", sa.Boolean(), nullable=False),
        sa.Column("universe_available", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("original_thesis", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_strategies_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategies")),
    )
    op.create_table(
        "strategy_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("canonical_hash", sa.String(length=64), nullable=False),
        sa.Column("canonical_json", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["strategies.id"], name=op.f("fk_strategy_versions_strategy_id_strategies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_versions")),
        sa.UniqueConstraint("strategy_id", "version", name="strategy_version"),
    )
    op.create_index(
        "ix_strategy_versions_canonical_hash", "strategy_versions", ["canonical_hash"], unique=False
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_version", sa.Integer(), nullable=False),
        sa.Column("strategy_hash", sa.String(length=64), nullable=False),
        sa.Column("data_mode", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("stages_completed", sa.JSON(), nullable=False),
        sa.Column("seeds", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_runs_project_id_projects")),
        sa.ForeignKeyConstraint(
            ["strategy_id", "strategy_version"],
            ["strategy_versions.strategy_id", "strategy_versions.version"],
            name="strategy_version_ref",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index("ix_runs_strategy_hash", "runs", ["strategy_hash"], unique=False)
    op.create_table(
        "artifact_index",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("store", sa.String(length=32), nullable=False),
        sa.Column("artifact_key", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_artifact_index_run_id_runs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifact_index")),
        sa.UniqueConstraint("run_id", "store", "artifact_key", name="run_store_key"),
    )
    op.create_index(op.f("ix_artifact_index_run_id"), "artifact_index", ["run_id"], unique=False)
    op.create_table(
        "evidence_verification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_evidence_verification_run_id_runs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_verification")),
        sa.UniqueConstraint("run_id", name=op.f("uq_evidence_verification_run_id")),
    )
    op.create_table(
        "failures",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_hash", sa.String(length=64), nullable=False),
        sa.Column("world_hash", sa.String(length=64), nullable=False),
        sa.Column("mechanism", sa.String(length=64), nullable=False),
        sa.Column("intensity", sa.Float(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("violated_predicates", sa.JSON(), nullable=False),
        sa.Column("seed_agreement", sa.String(length=32), nullable=False),
        sa.Column("execution_sensitive", sa.Boolean(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_failures_run_id_runs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_failures")),
    )
    op.create_index("ix_failures_mechanism", "failures", ["mechanism"], unique=False)
    op.create_index("ix_failures_run_id", "failures", ["run_id"], unique=False)
    op.create_index("ix_failures_strategy_hash", "failures", ["strategy_hash"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("inputs_frozen", sa.Boolean(), nullable=False),
        sa.Column("failure_json", sa.JSON(), nullable=True),
        sa.Column("result_ref", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "stage IN ('compile', 'resolve', 'approve', 'acquire_data', 'historical_backtest', 'calculate_metrics', 'stress_campaign', 'minimize_failure', 'adjacent_pass_search', 'exchange_replay', 'evidence_export', 'evidence_verify')",
            name=op.f("ck_jobs_stage_allowed"),
        ),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_jobs_state_allowed"),
        ),
        sa.CheckConstraint("attempts <= max_attempts", name=op.f("ck_jobs_attempts_le_max")),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_jobs_attempts_nonneg")),
        sa.CheckConstraint("max_attempts >= 1", name=op.f("ck_jobs_max_attempts_min")),
        sa.CheckConstraint("progress >= 0 AND progress <= 1", name=op.f("ck_jobs_progress_unit_interval")),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_jobs_run_id_runs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name="idempotency_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jobs")
    op.drop_index("ix_failures_strategy_hash", table_name="failures")
    op.drop_index("ix_failures_run_id", table_name="failures")
    op.drop_index("ix_failures_mechanism", table_name="failures")
    op.drop_table("failures")
    op.drop_table("evidence_verification")
    op.drop_index(op.f("ix_artifact_index_run_id"), table_name="artifact_index")
    op.drop_table("artifact_index")
    op.drop_index("ix_runs_strategy_hash", table_name="runs")
    op.drop_table("runs")
    op.drop_index("ix_strategy_versions_canonical_hash", table_name="strategy_versions")
    op.drop_table("strategy_versions")
    op.drop_table("strategies")
    op.drop_table("projects")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
