"""phase2_6_integrity_closure

Revision ID: c78d9eca0b19
Revises: c77dbd35bd12
Create Date: 2026-07-26 09:51:26.763864
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c78d9eca0b19"
down_revision: str | None = "c77dbd35bd12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("scope", "project_id", "idempotency_key", name="idempotency_scope_project_key"),
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_version", sa.Integer(), nullable=False),
        sa.Column("strategy_hash", sa.String(length=64), nullable=False),
        sa.Column("baseline_run_id", sa.String(length=64), nullable=True),
        sa.Column("base_panel_digest", sa.String(length=64), nullable=False),
        sa.Column("mechanisms", sa.JSON(), nullable=False),
        sa.Column("seeds", sa.JSON(), nullable=False),
        sa.Column("failure_predicates", sa.JSON(), nullable=False),
        sa.Column("confirmation_policy", sa.JSON(), nullable=False),
        sa.Column("requested_worlds", sa.Integer(), nullable=False),
        sa.Column("evaluated_worlds", sa.Integer(), nullable=False),
        sa.Column("predicate_failures", sa.Integer(), nullable=False),
        sa.Column("evaluation_errors", sa.Integer(), nullable=False),
        sa.Column("error_rate", sa.Float(), nullable=False),
        sa.Column("errors_by_mechanism", sa.JSON(), nullable=False),
        sa.Column("failure_rate_by_mechanism", sa.JSON(), nullable=False),
        sa.Column("result_manifest_key", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_campaigns_run_id_runs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index("ix_campaigns_project_id", "campaigns", ["project_id"], unique=False)
    op.create_index("ix_campaigns_strategy_hash", "campaigns", ["strategy_hash"], unique=False)
    op.create_table(
        "scenario_worlds",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("world_key", sa.String(length=128), nullable=False),
        sa.Column("mechanism", sa.String(length=64), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("intensity", sa.Float(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("diagnostics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name=op.f("fk_scenario_worlds_campaign_id_campaigns")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenario_worlds")),
        sa.UniqueConstraint("campaign_id", "world_key", name="campaign_world_key"),
    )
    op.create_index("ix_scenario_worlds_campaign_id", "scenario_worlds", ["campaign_id"], unique=False)
    op.create_table(
        "world_evaluations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("world_id", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("predicate_results", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name=op.f("fk_world_evaluations_campaign_id_campaigns")
        ),
        sa.ForeignKeyConstraint(
            ["world_id"], ["scenario_worlds.id"], name=op.f("fk_world_evaluations_world_id_scenario_worlds")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_world_evaluations")),
    )
    op.create_index("ix_world_evaluations_campaign_id", "world_evaluations", ["campaign_id"], unique=False)
    op.create_table(
        "adjacent_passes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("failure_id", sa.String(length=64), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("predicate_results", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("artifact_ref", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name=op.f("fk_adjacent_passes_campaign_id_campaigns")
        ),
        sa.ForeignKeyConstraint(
            ["failure_id"],
            ["world_evaluations.id"],
            name=op.f("fk_adjacent_passes_failure_id_world_evaluations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adjacent_passes")),
    )
    op.create_table(
        "minimization_trials",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("failure_id", sa.String(length=64), nullable=False),
        sa.Column("dimension", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("failed", sa.Boolean(), nullable=False),
        sa.Column("predicate_results", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name=op.f("fk_minimization_trials_campaign_id_campaigns")
        ),
        sa.ForeignKeyConstraint(
            ["failure_id"],
            ["world_evaluations.id"],
            name=op.f("fk_minimization_trials_failure_id_world_evaluations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_minimization_trials")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("minimization_trials")
    op.drop_table("adjacent_passes")
    op.drop_index("ix_world_evaluations_campaign_id", table_name="world_evaluations")
    op.drop_table("world_evaluations")
    op.drop_index("ix_scenario_worlds_campaign_id", table_name="scenario_worlds")
    op.drop_table("scenario_worlds")
    op.drop_index("ix_campaigns_strategy_hash", table_name="campaigns")
    op.drop_index("ix_campaigns_project_id", table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_table("idempotency_records")
    # ### end Alembic commands ###
