from __future__ import annotations

import numpy as np

from app.simulation import SimulationResult


def _autocorrelation(values: np.ndarray, lag: int = 1) -> float | None:
    if len(values) <= lag + 2 or np.std(values[:-lag]) == 0 or np.std(values[lag:]) == 0:
        return None
    return float(np.corrcoef(values[:-lag], values[lag:])[0, 1])


def _row(name: str, value: float | None, target: str, status: str, notes: str, source: str = "") -> dict:
    return {
        "name": name,
        "value": value,
        "target": target,
        "status": status,
        "notes": notes,
        "source": source,
    }


def build_realism_report(result: SimulationResult, symbol: str = "NOVA") -> dict:
    states = [frame["asset_states"][symbol] for frame in result.timeline]
    prices = np.asarray([state["mid_ticks"] for state in states], dtype=float)
    returns = np.diff(np.log(np.maximum(prices, 1)))
    spreads = np.asarray(
        [state["spread_ticks"] for state in states if state["spread_ticks"] is not None], dtype=float
    )
    depths = np.asarray([state["bid_depth"] + state["ask_depth"] for state in states], dtype=float)
    volumes = np.asarray([state["volume"] for state in states], dtype=float)
    kurtosis = (
        float(np.mean((returns - returns.mean()) ** 4) / (np.var(returns) ** 2) - 3)
        if len(returns) > 8 and np.var(returns)
        else None
    )
    return_ac = _autocorrelation(returns)
    abs_ac = _autocorrelation(np.abs(returns))
    volume_vol = (
        _autocorrelation(np.column_stack((volumes[1:], np.abs(returns))).sum(axis=1))
        if len(returns) > 4
        else None
    )
    signed = []
    for trade in result.trades:
        if trade["symbol"] == symbol:
            sign = (
                1
                if trade["buyer_id"].startswith("execution")
                else -1
                if trade["seller_id"].startswith("execution")
                else 0
            )
            signed.append(sign * trade["quantity"])
    flow_persistence = _autocorrelation(np.asarray(signed, dtype=float)) if len(signed) > 4 else None
    metrics = [
        _row(
            "Excess kurtosis",
            kurtosis,
            "> 0 (heavy tails)",
            "Partial" if kurtosis is not None and kurtosis > 0 else "Fail",
            "Prototype target is directional, not calibrated.",
            "Cont 2001; Bouchaud et al. 2009",
        ),
        _row(
            "Return autocorrelation lag 1",
            return_ac,
            "near 0",
            "Pass" if return_ac is not None and abs(return_ac) < 0.15 else "Partial",
            "Raw returns should have limited linear predictability.",
            "Cont 2001",
        ),
        _row(
            "Absolute-return autocorrelation lag 1",
            abs_ac,
            "> 0",
            "Pass" if abs_ac is not None and abs_ac > 0.05 else "Partial",
            "Directional volatility-clustering check.",
            "Cont 2001",
        ),
        _row(
            "Mean spread (ticks)",
            float(spreads.mean()) if len(spreads) else None,
            "> 0",
            "Pass" if len(spreads) and spreads.mean() > 0 else "Fail",
            "Spread is generated by resting quotes.",
        ),
        _row(
            "Mean displayed depth",
            float(depths.mean()) if len(depths) else None,
            "> 0",
            "Pass" if len(depths) and depths.mean() > 0 else "Fail",
            "Top configured levels on both sides.",
        ),
        _row(
            "Order-flow persistence",
            flow_persistence,
            "> 0",
            "Partial" if flow_persistence is not None and flow_persistence > 0 else "Fail",
            "Signed execution-agent flow proxy; broader participant classification is deferred.",
        ),
        _row(
            "Volume-volatility relationship",
            volume_vol,
            "positive",
            "Not evaluated",
            "Current sample is too short for a defensible classification.",
        ),
        _row(
            "Cross-asset correlation",
            None,
            "regime-dependent",
            "Not evaluated",
            "Paths are available but the quick demo sample is insufficient for calibration.",
        ),
        _row(
            "Impact decay",
            None,
            "partial reversion",
            "Not evaluated",
            "Requires dedicated metaorder alignment across repetitions.",
        ),
    ]
    return {
        "classification": "component diagnostics only",
        "metrics": metrics,
        "disclaimer": "These checks do not establish institutional realism or fitness for live trading.",
    }
